name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: |
          cd client && npm install
          cd ../server && npm install

      - name: Run linting
        run: |
          cd client && npm run lint
          cd ../server && npm run lint

      - name: Run tests
        run: |
          cd client && npm test
          cd ../server && npm test

      - name: Build
        run: |
          cd client && npm run build
          cd ../server && npm run build
